image: elixir:latest

before_script:
  - elixir --version
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

mix:
  script:
  - mix test
  - mix check

cache:
  paths:
    - _build
    - deps